---
name: linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-linting:
    uses: telekom-mms/.github/.github/workflows/terraform_linting.yml@d1894e54358f72c951488c8f998d36eb923df2b6 # main
